---
title: "3章_回帰分析と共分散分析"
output: html_document
date: '2022-05-15'
---
# データ（数学の試験成績）の読込み
$x1$は入学試験の点数、$y3$は期末試験の点数、$t1$は補修授業受講（処置）の有無、$y0t$は潜在的結果変数0（すべての学生が補修授業を受けなかった場合の期末試験の点数）、$y1t$は潜在的結果変数1（すべての学生が補修授業を受けた場合の期末試験の点数）を表す。
```{r}
rm(list = ls())
d <- read.csv("data03.csv")
attach(d)
```
# 平均処置効果の確認
```{r}
mean(y3[t1==1]) - mean(y3[t1==0])　# ナイーブな推定値
mean(y1t) - mean(y0t)　# 平均処置効果の真値
```

# 共分散分析でモデリング
共分散分析の式は以下の通り。$T_i$は処置の割付けを0または1で表すダミー変数である。
$$
　\hat Y_i = \hat \beta_0 + \hat \beta_1 X_i + \hat \beta_2 T_i
$$
```{r}
model <- lm(y3 ~ x1 + t1)　# 共分散分析
summary(model)
```
t1の回帰係数が$\hat \beta_2$で、平均処置効果を捉えており、9.82と推定された。

confint関数を使って95%信頼区間を表示する。
```{r}
confint(model, level = 0.95)
```
t1の信頼区間は8.91〜10.72で、平均処置効果は9.82のため、無視可能な割付けであれば、共変量に条件付けることで、平均処置効果が適切に推定できている。

# 散布図
```{r}
plot(x1[t1==0], y3[t1==0], xlim=c(60, 100), ylim=c(60, 100), pch=4)
par(new=TRUE)
plot(x1[t1==1], y3[t1==1], xlim=c(60, 100), ylim=c(60, 100), pch=2)
b0 <- summary(model)$coefficient[1]
b1 <- summary(model)$coefficient[2]
b2 <- summary(model)$coefficient[3]
abline(a=b0, b=b1)
abline(a=b0 + b2, b=b1)
```
```{r}
library(tidyverse)
ggplot() +
  geom_point(data = d, mapping = aes(x=x1, y=y3, shape=factor(t1))) +
  geom_smooth(data = d, mapping = aes(x=x1, y=y3, group=factor(t1)), method = "lm") +
  theme_gray(base_family = "HiraginoSans-W3") +
  labs(x="入学試験", y="期末試験", shape="処置の有無")

```

